### PR TITLE
Add support for persistent connections

### PR DESCRIPTION
**Pull request by dada-amater**
Please allow to use persistent connections to significantly reduce rabbitmq load.

### CODE REVIEW

**Comment by dada-amater** [comment]
@paveljanda Do you plan to merge this PR?

**Comment by paveljanda** [comment]
Oh I don't think that that change in composer.json will pass. :)

**Comment by paveljanda** [comment]
When you change it, I can merge this PR.

**Comment by paveljanda** [comment]
@dada-amater Do you intent to change this PR?

**Comment by dada-amater** [comment]
Will make separate branch for you. Because this PR was not merged, I had had to fork this package.

**Comment by paveljanda** [comment]
Merged. @dada-amater Can I close this issue now?

**Pull request closed without merging**
