### PR TITLE
unify syntax in readmes

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by paveljanda** [comment]
Could you please remove the space indentation and put back tabs? Thanks 👍

**Comment by petrparolek** [comment]
YAML cannot contain tabs.

**Comment by paveljanda** [comment]
Yes but this is neon, right?

**Comment by petrparolek** [comment]
what do you think @f3l1x ?  Then I would have to reformaed  readmes in all repos!

**Comment by paveljanda** [comment]
Screenshot 2021-03-09 at 20 34 19

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3520

Why don't we use native neon with tabs??

**Comment by paveljanda** [comment]
@petrparolek I will @petrparolek Let's take that the easy way - I will transform to `neon` and tabs repositories that were once Ublaboo (authored by me). Will that help you?

**Comment by petrparolek** [comment]
I will add commits to all PR

**Comment by paveljanda** [comment]
Thanks

**Pull request merged**
